CREATE DATABASE RatesBase;

USE RatesBase;

CREATE TABLE rates (curr1 nchar(3), curr2 nchar(3), rate decimal(18,2));

INSERT INTO rates VALUES('AED','AED',1);
INSERT INTO rates VALUES('AED','AFN',20);
INSERT INTO rates VALUES('AED','ALL',815);
INSERT INTO rates VALUES('AED','AMD',826);
INSERT INTO rates VALUES('AED','ANG',866);
INSERT INTO rates VALUES('AED','AOA',939);
INSERT INTO rates VALUES('AED','ARS',935);
INSERT INTO rates VALUES('AED','AUD',396);
INSERT INTO rates VALUES('AED','AWG',102);
INSERT INTO rates VALUES('AED','AZN',602);
INSERT INTO rates VALUES('AED','BAM',141);
INSERT INTO rates VALUES('AED','BBD',993);
INSERT INTO rates VALUES('AED','BDT',347);
INSERT INTO rates VALUES('AED','BGN',648);
INSERT INTO rates VALUES('AED','BHD',359);
INSERT INTO rates VALUES('AED','BIF',271);
INSERT INTO rates VALUES('AED','BMD',192);
INSERT INTO rates VALUES('AED','BND',949);
INSERT INTO rates VALUES('AED','BOB',219);
INSERT INTO rates VALUES('AED','BOV',28);
INSERT INTO rates VALUES('AED','BRL',45);
INSERT INTO rates VALUES('AED','BSD',99);
INSERT INTO rates VALUES('AED','BTN',384);
INSERT INTO rates VALUES('AED','BWP',382);
INSERT INTO rates VALUES('AED','BYN',702);
INSERT INTO rates VALUES('AED','BZD',831);
INSERT INTO rates VALUES('AED','CAD',160);
INSERT INTO rates VALUES('AED','CDF',190);
INSERT INTO rates VALUES('AED','CHE',554);
INSERT INTO rates VALUES('AED','CHF',317);
INSERT INTO rates VALUES('AED','CHW',186);
INSERT INTO rates VALUES('AED','CLF',275);

SELECT * FROM rates;